instance: cwa

default_field_map: &default_field_map
  id:
    column:
    ab_type:
  people: &default_people_map
      first_name: First Name
      middle_name: Middle Name
      last_name: Last Name

upload-test:
  campaign_name: Activision Blizzard
  fields:
    <<: *default_field_map
