instance: cwatest

default_field_map: &default_field_map
  id:
    column: id
    ab_type: Custom ID
  people: &default_people_map
      first_name: First Name
      middle_name: Middle Name
      last_name: Last Name

upload-test:
  campaign_name: Activision Blizzard
  fields:
    <<: *default_field_map
